export const RESET_PASS_REQUEST = 'RESET_PASS_REQUEST'
export const RESET_PASS_REQUEST_SUCCESS = 'RESET_PASS_REQUEST_SUCCESS'
export const RESET_PASS_REQUEST_FAILED = 'RESET_PASS_REQUEST_FAILED'
export const SET_INIT_STATE_RESET_PASS = 'SET_INIT_STATE_RESET_PASS'
