export const RESTORE_PASS_REQUEST = 'RESTORE_PASS_REQUEST'
export const RESTORE_PASS_REQUEST_SUCCESS = 'RESTORE_PASS_REQUEST_SUCCESS'
export const RESTORE_PASS_REQUEST_FAILED = 'RESTORE_PASS_REQUEST_FAILED'