export const RESTORE_PASS_REQUEST = 'RESTORE_PASS_REQUEST'
export const RESTORE_PASS_REQUEST_SUCCESS = 'RESTORE_PASS_REQUEST_SUCCESS'
export const RESTORE_PASS_REQUEST_FAILED = 'RESTORE_PASS_REQUEST_FAILED'
export const SET_INIT_STATE_RESTORE_PASS = 'SET_INIT_STATE_RESTORE_PASS'
