export const GET_USER_REQUEST = 'GET_USER_REQUEST'
export const GET_USER_REQUEST_SUCCESS = 'GET_USER_REQUEST_SUCCESS'
export const GET_USER_REQUEST_FAILED = 'GET_USER_REQUEST_FAILED'

export const UPDATE_USER_REQUEST = 'UPDATE_USER_REQUEST'
export const UPDATE_USER_REQUEST_SUCCESS = 'UPDATE_USER_REQUEST_SUCCESS'
export const UPDATE_USER_REQUEST_FAILED = 'UPDATE_USER_REQUEST_FAILED'

export const SET_USER = 'SET_USER'
